### ISSUE TITLE
Commands not assigned to Correct variables.

### ISSUE THREAD

**Issue by lukelane124** [Byvire/load-cell-reader#1]
[take_data.txt](https://github.com/Byvire/load-cell-reader/files/551366/take_data.txt)
In line 31 The command that should be ACTIVE is written as ACIVE. This caused a few issues in the last days, trying to hunt down the source of an error.

**Comment by Byvire** [comment]
I finally noticed and fixed this. Next time feel free to send a pull request with the typo fix.
